spring.application.name=chatapp

# MySQL Datasource
# The "?createDatabaseIfNotExist=true" part will create 'car_rentals_db' on first launch.
spring.datasource.url=jdbc:mysql://localhost:3306/car_rentals_db?createDatabaseIfNotExist=true
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Boot will automatically run schema.sql on startup
# if it detects it in the resources folder.
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always